WebApplication1/Controllers/DotNetAwesomeDataTablesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

using System.Linq.Dynamic;

namespace WebApplication1.Controllers
{
    public class DotNetAwesomeDataTablesController : Controller
    {
        //http://www.dotnetawesome.com/2016/12/crud-operation-using-datatables-aspnet-mvc.html

        // GET: DataTablesClient
        public ActionResult Index()
        {
            return View();
        }

        // GET: DataTables Server side pagination and sorting
        public ActionResult Index2()
        {
            return View();
        }

        // GET: DataTables Server side pagination, sorting and filtering
        public ActionResult Index3()
        {
            return View();
        }
         
        // GET: DataTables Server side pagination, sorting, filtering and crud
        //public ActionResult Index4()
        //{
        //    return View();
        //}

        public ActionResult GetContacts()
        {
            using (PracticeEntities db = new PracticeEntities())
            {
                var contacts = db.Contacts.ToList();
                return Json(new { data = contacts }, JsonRequestBehavior.AllowGet);
            }
        }

        [HttpPost]
        public ActionResult GetContactsServersidePagingSorting()
        {
            var draw = Request.Form.GetValues("draw").FirstOrDefault();
            var start = Request.Form.GetValues("start").FirstOrDefault();
            var length = Request.Form.GetValues("length").FirstOrDefault();
            //Find Order Column
            var sortColumn = Request.Form.GetValues("columns[" + Request.Form.GetValues("order[0][column]").FirstOrDefault() + "][name]").FirstOrDefault();
            var sortColumnDir = Request.Form.GetValues("order[0][dir]").FirstOrDefault();


            int pageSize = length != null ? Convert.ToInt32(length) : 0;
            int skip = start != null ? Convert.ToInt32(start) : 0;
            int recordsTotal = 0;
            using (PracticeEntities db = new PracticeEntities())
            {
                // dc.Configuration.LazyLoadingEnabled = false; // if your table is relational, contain foreign key
                var v = (from a in db.Contacts select a);

                //SORT
                if (!(string.IsNullOrEmpty(sortColumn) && string.IsNullOrEmpty(sortColumnDir)))
                {
                    v = v.OrderBy(sortColumn + " " + sortColumnDir);
                }

                recordsTotal = v.Count();
                var data = v.Skip(skip).Take(pageSize).ToList();
                return Json(new { draw = Convert.ToInt32(draw), recordsFiltered = recordsTotal, recordsTotal = recordsTotal, data = data }, JsonRequestBehavior.AllowGet);
            }
        }

        [HttpPost]
        public ActionResult GetContactsServersidePagingSortingFiltering()
        {
            var draw = Request.Form.GetValues("draw").FirstOrDefault();
            var start = Request.Form.GetValues("start").FirstOrDefault();
            var length = Request.Form.GetValues("length").FirstOrDefault();
            //Find Order Column
            var sortColumn = Request.Form.GetValues("columns[" + Request.Form.GetValues("order[0][column]").FirstOrDefault() + "][name]").FirstOrDefault();
            var sortColumnDir = Request.Form.GetValues("order[0][dir]").FirstOrDefault();

            //find search columns info
            var contactName = Request.Form.GetValues("columns[0][search][value]").FirstOrDefault();
            var state = Request.Form.GetValues("columns[7][search][value]").FirstOrDefault();

            int pageSize = length != null ? Convert.ToInt32(length) : 0;
            int skip = start != null ? Convert.ToInt32(start) : 0;
            int recordsTotal = 0;
            using (PracticeEntities db = new PracticeEntities())
            {
                // dc.Configuration.LazyLoadingEnabled = false; // if your table is relational, contain foreign key
                var v = (from a in db.Contacts select a);

                //SEARCHING...
                if (!string.IsNullOrEmpty(contactName))
                {
                    v = v.Where(a => a.FirstName.Contains(contactName));
                }
                if (!string.IsNullOrEmpty(state))
                {
                    v = v.Where(a => a.State == state);
                }

                //SORT
                if (!(string.IsNullOrEmpty(sortColumn) && string.IsNullOrEmpty(sortColumnDir)))
                {
                    v = v.OrderBy(sortColumn + " " + sortColumnDir);
                }

                recordsTotal = v.Count();
                var data = v.Skip(skip).Take(pageSize).ToList();
                return Json(new { draw = Convert.ToInt32(draw), recordsFiltered = recordsTotal, recordsTotal = recordsTotal, data = data }, JsonRequestBehavior.AllowGet);
            }
        }

        //[HttpPost]
        //public ActionResult LoadData()
        //{
        //    try
        //    {
        //        //Creating instance of DatabaseContext class  
        //        using (PracticeEntities _context = new PracticeEntities())
        //        {
        //            var draw = Request.Form.GetValues("draw").FirstOrDefault();
        //            var start = Request.Form.GetValues("start").FirstOrDefault();
        //            var length = Request.Form.GetValues("length").FirstOrDefault();
        //            var sortColumn = Request.Form.GetValues("columns[" + Request.Form.GetValues("order[0][column]").FirstOrDefault() + "][name]").FirstOrDefault();
        //            var sortColumnDir = Request.Form.GetValues("order[0][dir]").FirstOrDefault();
        //            var searchValue = Request.Form.GetValues("search[value]").FirstOrDefault();


        //            //Paging Size (10,20,50,100)    
        //            int pageSize = length != null ? Convert.ToInt32(length) : 0;
        //            int skip = start != null ? Convert.ToInt32(start) : 0;
        //            int recordsTotal = 0;

        //            // Getting all Customer data    
        //            var customerData = (from tempcustomer in _context.Contacts
        //                                select tempcustomer);

        //            //Sorting    
        //            if (!(string.IsNullOrEmpty(sortColumn) && string.IsNullOrEmpty(sortColumnDir)))
        //            {
        //                customerData = customerData.OrderBy(sortColumn + " " + sortColumnDir);
        //            }
        //            //Search    
        //            if (!string.IsNullOrEmpty(searchValue))
        //            {
        //                customerData = customerData.Where(m => m.FirstName == searchValue ||
        //                                                       m.LastName == searchValue ||
        //                                                       m.Email == searchValue ||
        //                                                       m.City == searchValue ||
        //                                                       m.State == searchValue ||
        //                                                       m.Zip == searchValue);
        //            }

        //            //total number of rows count     
        //            recordsTotal = customerData.Count();
        //            //Paging     
        //            var data = customerData.Skip(skip).Take(pageSize).ToList();
        //            //Returning Json Data    
        //            return Json(new { draw = Convert.ToInt32(draw), recordsFiltered = recordsTotal, recordsTotal = recordsTotal, data = data });
        //        }
        //    }
        //    catch (Exception)
        //    {
        //        throw;
        //    }

        //}

        //[HttpGet]
        //public ActionResult Save(int id)
        //{
        //    using (PracticeEntities dc = new PracticeEntities())
        //    {
        //        var v = dc.Contacts.Where(a => a.Id == id).FirstOrDefault();
        //        return View(v);
        //    }
        //}

        //[HttpPost]
        //public ActionResult Save(Contact contact)
        //{
        //    bool status = false;
        //    if (ModelState.IsValid)
        //    {
        //        using (PracticeEntities dc = new PracticeEntities())
        //        {
        //            if (contact.Id > 0)
        //            {
        //                //Edit 
        //                var v = dc.Contacts.Where(a => a.Id == contact.Id).FirstOrDefault();
        //                if (v != null)
        //                {
        //                    v.FirstName = contact.FirstName;
        //                    v.LastName = contact.LastName;
        //                    v.Email = contact.Email;
        //                    v.PhonePrimary = contact.PhonePrimary;
        //                    v.PhoneSecondary = contact.PhoneSecondary;
        //                    v.Birthday = contact.Birthday;
        //                    v.StreetAddress1 = contact.StreetAddress1;
        //                    v.StreetAddress2 = contact.StreetAddress2;
        //                    v.City = contact.City;
        //                    v.State = contact.State;
        //                    v.Zip = contact.Zip;
        //                }
        //            }
        //            else
        //            {
        //                //Save
        //                dc.Contacts.Add(contact);
        //            }
        //            dc.SaveChanges();
        //            status = true;
        //        }
        //    }
        //    return new JsonResult { Data = new { status = status } };
        //}

        //[HttpGet]
        //public ActionResult Delete(int id)
        //{
        //    using (PracticeEntities dc = new PracticeEntities())
        //    {
        //        var v = dc.Contacts.Where(a => a.Id == id).FirstOrDefault();

WebApplication1/Views/DotNetAwesomeDataTables/Delete.cshtml
@model WebApplication1.Contact

<h2>Delete Contact</h2>
@using (Html.BeginForm("delete", "DotNetAwesomeDataTables", FormMethod.Post, new { id = "popupForm" }))
{
    @Html.HiddenFor(a => a.Id)
    <div class="form-group">
        <label>First Name</label>
        <p>@Model.FirstName</p>
    </div>

    <div class="form-group">
        <label>Last Name</label>
        <p>@Model.LastName</p>
    </div>

    <div class="form-group">
        <label>Email</label>
        <p>@Model.Email</p>
    </div>

    <div class="form-group">
        <label>Primary Phone</label>
        <p>@Model.PhonePrimary</p>
    </div>

    <div class="form-group">
        <label>Secodary Phone</label>
        <p>@Model.PhoneSecondary</p>
    </div>

    <div class="form-group">
        <label>Brithdate</label>
        <p>@Model.Birthday</p>
    </div>

    <div class="form-group">
        <label>Address1</label>
        <p>@Model.StreetAddress1</p>
    </div>

    <div class="form-group">
        <label>Address2</label>
        <p>@Model.StreetAddress2</p>
    </div>

    <div class="form-group">
        <label>City</label>
        <p>@Model.City</p>
    </div>

    <div class="form-group">
        <label>State</label>
        <p>@Model.State</p>
    </div>

    <div class="form-group">
        <label>Zipcode</label>
        <p>@Model.Zip</p>
    </div>

    <div>
        <input type="submit" value="Delete" />
    </div>
}

WebApplication1/Views/DotNetAwesomeDataTables/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<h2>Jquery DataTables Client side processing</h2>

<table id="contactsTable">
    <thead>
        <tr>
            <td>First Name</td>
            <td>Last Name</td>
            <td>Email</td>
            <td>Primary Phone</td>
            <td>Secondary Phone</td>
            <td>Birth Date</td>
            <td>City</td>
            <td>State</td>
            <td>Zipcode</td>
        </tr>
    </thead>
</table>

<link href="https://cdn.datatables.net/1.10.20/css/jquery.dataTables.min.css" rel="stylesheet" />

@section Scripts{
    <script src="https://cdn.datatables.net/1.10.20/js/jquery.dataTables.min.js"></script>

    <script>
        $(document).ready(function () {
            $('#contactsTable').DataTable({
                ajax: {
                    url: "/DotNetAwesomeDataTables/GetContacts",
                    type: "GET",
                    datatype: "json",
                    //"dataSrc": ""
                },
                "columns": [
                    { data: "FirstName" },
                    { data: "LastName" },
                    { data: "Email" },
                    { data: "PhonePrimary" },
                    { data: "PhoneSecondary" },
                    { data: "Birthday" },
                    { data: "City" },
                    { data: "State" },
                    { data: "Zip" }
                ]
            });
        });
    </script>
}

WebApplication1/Views/DotNetAwesomeDataTables/Index2.cshtml
@{
    ViewBag.Title = "Index2";
}

<h2>jQuery Datatable server side pagination and sorting in ASP.NET MVC application</h2>

<table id="contactsTable">
    <thead>
        <tr>
            <td>First Name</td>
            <td>Last Name</td>
            <td>Email</td>
            <td>Primary Phone</td>
            <td>Secondary Phone</td>
            <td>Birth Date</td>
            <td>City</td>
            <td>State</td>
            <td>Zipcode</td>
        </tr>
    </thead>
</table>

<link href="https://cdn.datatables.net/1.10.20/css/jquery.dataTables.min.css" rel="stylesheet" />

@section Scripts{
    <script src="https://cdn.datatables.net/1.10.20/js/jquery.dataTables.min.js"></script>

    <script>
        $(document).ready(function () {
            $('#contactsTable').DataTable({

                processing: true, // For showing progress bar
                serverSide: true, // For process server side
                filter: false, // For disabling filter (search box)
                orderMulti: false, // Now we can sort one column at a time

                ajax: {
                    url: "/DotNetAwesomeDataTables/GetContactsServersidePagingSorting",
                    type: "POST",
                    datatype: "json"
                    //"dataSrc": ""
                },
                "columns": [
                    { data: "FirstName", name: "FirstName" },
                    { data: "LastName", name: "LastName" },
                    { data: "Email", name: "Email" },
                    { data: "PhonePrimary", name: "PhonePrimary" },
                    { data: "PhoneSecondary", name: "PhoneSecodary" },
                    { data: "Birthday", name: "Birthday" },
                    { data: "City", name: "City" },
                    { data: "State", name: "State" },
                    { data: "Zip", name: "Zip" }
                ]
            });
        });
    </script>
}

WebApplication1/Views/DotNetAwesomeDataTables/Index3.cshtml
@{
    ViewBag.Title = "Index3";
}

<h2>implement custom multicolumn server-side filtering in jQuery dataTables</h2>
<div style="width:90%; margin:0 auto">
    @* Search Area *@
    <div style="background-color:#f5f5f5; padding:20px">
        <h2>Search Panel</h2>
        <table>
            <tbody>
                <tr>
                    <td>Contact Name</td>
                    <td><input type="text" id="txtContactName" /></td>
                    <td>Country</td>
                    <td>
                        <select id="ddState" style="width:200px">
                            <option value="">All States</option>
                            <option value="Gujarat">Gujarat</option>
                            <option value="Maharashtra">Maharashtra</option>
                            <option value="Karnatak">Karnatak</option>
                        </select>
                        @* Here I have made this select box with some static data for make this example simpler.
                            You can fill it from database data *@
                    </td>
                    <td>
                        <input type="button" value="Search" id="btnSearch" />
                    </td>
                </tr>
            </tbody>
        </table>
    </div>
    @* jQuery DataTables *@
    <div>
        <table id="contactsTable">
            <thead>
                <tr>
                    <td>First Name</td>
                    <td>Last Name</td>
                    <td>Email</td>
                    <td>Primary Phone</td>
                    <td>Secondary Phone</td>
                    <td>Birth Date</td>
                    <td>City</td>
                    <td>State</td>
                    <td>Zipcode</td>
                </tr>
            </thead>
        </table>
    </div>
</div>

<link href="https://cdn.datatables.net/1.10.20/css/jquery.dataTables.min.css" rel="stylesheet" />

@section Scripts{
    <script src="https://cdn.datatables.net/1.10.20/js/jquery.dataTables.min.js"></script>

    <script>
        $(document).ready(function () {
            $('#contactsTable').DataTable({

                processing: true, // For showing progress bar
                serverSide: true, // For process server side
                filter: true,
                orderMulti: false, // Now we can sort one column at a time
                dom: '<"top"i>rt<"bottom"lp><"clear">', // for hide default global search box // little confusion? don't worry I explained in the tutorial website

                ajax: {
                    url: "/DotNetAwesomeDataTables/GetContactsServersidePagingSortingFiltering",
                    type: "POST",
                    datatype: "json"
                    //"dataSrc": ""
                },
                "columns": [
                    { data: "FirstName", name: "FirstName", "autoWidth": true },
                    { data: "LastName", name: "LastName", "autoWidth": true },
                    { data: "Email", name: "Email", "autoWidth": true },
                    { data: "PhonePrimary", name: "PhonePrimary", "autoWidth": true },
                    { data: "PhoneSecondary", name: "PhoneSecodary", "autoWidth": true },
                    { data: "Birthday", name: "Birthday", "autoWidth": true },
                    { data: "City", name: "City", "autoWidth": true },
                    { data: "State", name: "State", "autoWidth": true },
                    { data: "Zip", name: "Zip", "autoWidth": true }
                ]
            });

            oTable = $('#contactsTable').DataTable();
            $('#btnSearch').click(function () {
                //Apply search for Employee Name // DataTable column index 0
                oTable.columns(0).search($('#txtContactName').val().trim());
                //Apply search for Country // DataTable column index 3
                oTable.columns(7).search($('#ddState').val().trim());
                //hit search on server
                oTable.draw();
            });
        });
    </script>
}

WebApplication1/Views/DotNetAwesomeDataTables/Index4.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>
<html>
<head>
    <title>Full CRUD operation using datatables in ASP.NET MVC</title>
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" />
    <link href="~/Content/DataTables/css/jquery.dataTables.min.css" rel="stylesheet" />
    <link href="~/Content/themes/base/jquery-ui.min.css" rel="stylesheet" />
    <style>
        span.field-validation-error {
            color: red;
        }
    </style>
</head>
<body>
    <div style="width:90%; margin:0 auto" class="tablecontainer">
        <a class="popup btn btn-primary" href="/DotNetAwesomeDataTables/save/0" style="margin-bottom:20px; margin-top:20px;">Add New Contact</a>
        <table id="ContactsDataTable">
            <thead>
                <tr>
                    <th>ContactId</th>
                    <th>First Name</th>
                    <th>Last Name</th>
                    <th>Email</th>
                    <th>Primary Phone</th>
                    <th>Secondary Phone</th>
                    <th>Birth Date</th>
                    <th>City</th>
                    <th>State</th>
                    <th>Zipcode</th>
                    <th>Edit</th>
                    <th>Delete</th>
                </tr>
            </thead>
        </table>
    </div>

    <script src="~/Scripts/jquery-1.12.4.min.js"></script>
    <script src="~/Scripts/jquery.validate.min.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
    <script src="~/Scripts/DataTables/jquery.dataTables.min.js"></script>
    <script src="~/Scripts/jquery-ui-1.12.1.min.js"></script>

    <script>
        $(document).ready(function () {
            var oTable = $("#ContactsDataTable").DataTable({

                "processing": true, // for show progress bar
                "serverSide": true, // for process server side
                "filter": true, // this is for disable filter (search box)
                "orderMulti": false, // for disable multiple column at once
                //"pageLength": 5,

                "ajax": {
                    "url": "/DotNetAwesomeDataTables/LoadData",
                    "type": "POST",
                    "datatype": "json"
                },

                "columnDefs":
                [
                    {
                        "targets": [0],
                        "visible": false,
                        "searchable": false
                    },
                    {
                        "targets": [4],
                        "searchable": false,
                        "orderable": false
                    },
                    {
                        "targets": [5],
                        "searchable": false,
                        "orderable": false
                    },
                    {
                        "targets": [6],
                        "searchable": false,
                        "orderable": true
                    },
                    {
                        "targets": [10],
                        "searchable": false,
                        "orderable": false
                    },
                    {
                        "targets": [11],
                        "searchable": false,
                        "orderable": false
                    }
                ],

                "columns": [
                    { data: "Id", name: "Id", "autoWidth": true },
                    { data: "FirstName", name: "FirstName", "autoWidth": true },
                    { data: "LastName", name: "LastName", "autoWidth": true },
                    { data: "Email", name: "Email", "autoWidth": true },
                    { data: "PhonePrimary", name: "PhonePrimary", "autoWidth": true },
                    { data: "PhoneSecondary", name: "PhoneSecodary", "autoWidth": true },
                    { data: "Birthday", name: "Birthday", "autoWidth": true },
                    { data: "City", name: "City", "autoWidth": true },
                    { data: "State", name: "State", "autoWidth": true },
                    { data: "Zip", name: "Zip", "autoWidth": true },
                    {
                        data: "Id", "width": "50px", render: function (data) {
                            return '<a class="popup" href="/DotNetAwesomeDataTables/save/' + data + '">Edit</a>';
                        }
                    },
                    {
                        data: "Id", "width": "50px", render: function (data) {
                            return '<a class="popup" href="/DotNetAwesomeDataTables/delete/' + data + '">Delete</a>';
                        }
                    }
                ]

            });

            $('.tablecontainer').on('click', 'a.popup', function (e) {
                e.preventDefault();
                OpenPopup($(this).attr('href'));
            })

            function OpenPopup(pageUrl) {
                var $pageContent = $('<div/>');
                $pageContent.load(pageUrl, function () {
                    $('#popupForm', $pageContent).removeData('validator');
                    $('#popupForm', $pageContent).removeData('unobtrusiveValidation');
                    $.validator.unobtrusive.parse('form');

                });

                $dialog = $('<div class="popupWindow" style="overflow:auto"></div>')
                    .html($pageContent)
                    .dialog({
                        draggable: false,
                        autoOpen: false,
                        resizable: false,
                        model: true,
                        title: 'Popup Dialog',
                        height: 550,
                        width: 600,
                        close: function () {
                            $dialog.dialog('destroy').remove();
                        }
                    })

                $('.popupWindow').on('submit', '#popupForm', function (e) {
                    var url = $('#popupForm')[0].action;
                    $.ajax({
                        type: "POST",
                        url: url,
                        data: $('#popupForm').serialize(),
                        success: function (data) {
                            if (data.status) {
                                $dialog.dialog('close');
                                oTable.ajax.reload();
                            }
                        }
                    })

                    e.preventDefault();
                })
                $dialog.dialog('open');
            }

        });

        //function DeleteData(ContactID) {
        //    if (confirm("Are you sure you want to delete ...?")) {
        //        Delete(ContactID);
        //    }
        //    else {
        //        return false;
        //    }
        //}

        //function Delete(ContactID) {
        //    var url = "/DataTablesCrud/DeleteContact";
        //    $.post(url, { ID: ContactID }, function (data) {
        //        if (data == "Deleted") {
        //            alert("Delete Cusomer !");
        //            oTable = $('#demoGrid').DataTable();
        //            oTable.draw();
        //        }
        //        else {
        //            alert("Something Went Wrong!");
        //        }
        //    });
        //}

    </script>

</body>
</html>

WebApplication1/Views/DotNetAwesomeDataTables/Save.cshtml
@model WebApplication1.Contact
<h2>Save</h2>
@using (Html.BeginForm("save", "DotNetAwesomeDataTables", FormMethod.Post, new { id = "popupForm" }))
{
    if (Model != null && Model.Id > 0)
    {
        @Html.HiddenFor(a => a.Id)
    }

    <div class="form-group">
        <label>First Name</label>
        @Html.TextBoxFor(a => a.FirstName, new { @class = "form-control" })
        @Html.ValidationMessageFor(a => a.FirstName)
    </div>
    <div class="form-group">
        <label>Last Name</label>
        @Html.TextBoxFor(a => a.LastName, new { @class = "form-control" })
        @Html.ValidationMessageFor(a => a.LastName)
    </div>
    <div class="form-group">
        <label>Email</label>
        @Html.TextBoxFor(a => a.Email, new { @class = "form-control" })
        @Html.ValidationMessageFor(a => a.Email)
    </div>
    <div class="form-group">
        <label>Primary Phone</label>
        @Html.TextBoxFor(a => a.PhonePrimary, new { @class = "form-control" })
        @Html.ValidationMessageFor(a => a.PhonePrimary)
    </div>
    <div class="form-group">
        <label>Secondary Phone</label>
        @Html.TextBoxFor(a => a.PhoneSecondary, new { @class = "form-control" })
        @Html.ValidationMessageFor(a => a.PhoneSecondary)
    </div>
    <div class="form-group">
        <label>Birthdate</label>
        @Html.TextBoxFor(a => a.Birthday, new { @class = "form-control" })
        @Html.ValidationMessageFor(a => a.Birthday)
    </div>
    <div class="form-group">
        <label>Address1</label>
        @Html.TextBoxFor(a => a.StreetAddress1, new { @class = "form-control" })
        @Html.ValidationMessageFor(a => a.StreetAddress1)
    </div>
    <div class="form-group">
        <label>Address2</label>
        @Html.TextBoxFor(a => a.StreetAddress2, new { @class = "form-control" })
        @Html.ValidationMessageFor(a => a.StreetAddress2)
    </div>
    <div class="form-group">
        <label>City</label>
        @Html.TextBoxFor(a => a.City, new { @class = "form-control" })
        @Html.ValidationMessageFor(a => a.City)
    </div>
    <div class="form-group">
        <label>Country</label>
        @Html.TextBoxFor(a => a.State, new { @class = "form-control" })
        @Html.ValidationMessageFor(a => a.State)
    </div>
    <div class="form-group">
        <label>Zipcode</label>
        @Html.TextBoxFor(a => a.Zip, new { @class = "form-control" })
        @Html.ValidationMessageFor(a => a.Zip)
    </div>

    <div>
        <input type="submit" value="Save" />
    </div>
}